server:
  port: 8093
  servlet:
    context-path: /
  ssl:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true #注册服务的ip
    leaseRenewalIntervalInSeconds: 5 #心跳间隔时间,默认是30秒
    leaseExpirationDurationInSeconds: 10 #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
  client:
    registryFetchIntervalSeconds: 5 # 定时刷新本地缓存时间
    register-with-eureka: true #使用Eureka注册服务
    fetch-registry: true #在本地缓存注册表

spring:
  application:
    name: helios-base-service
  cloud:
    config:
     # uri: http://localhost:8088/
      discovery:
        enabled: true
        serviceId: config-server
     # profile: test
      profile: dev
      fail-fast: true
      retry:
        multiplier: 1000
        max-attempts: 10



feign:
  hystrix:
    enabled: true

ribbon:
  #  ribbon重试超时时间
  ConnectTimeout: 60000
  #  建立连接后的超时时间
  ReadTimeout: 60000
  #  对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #  切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #  对当前实例的重试次数
  MaxAutoRetries: 1
  # Ribbon缓存时间
  ServerListRefreshInterval: 5000
  eureka:
    enable: true