spring:
  application:
    name: config-server
#    profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apprilsmile/appril-springcloud.git
          default-label: master
          force-pull: true
          search-paths: 'helios-config/src/main/resources/configs/{profile}'
server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true #注册服务的ip
  client:
    register-with-eureka: true #使用Eureka注册服务
    fetch-registry: true #在本地缓存注册表
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #Eureka服务位置

