spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: #
      max-request-size: 256MB
      max-file-size: 256MB
      resolve-lazily: false



zuul.routes.base.path: /base/**   #这里是映射路径
zuul.routes.base.service-id: helios-base-service   #指定服务名称
zuul.routes.base.stripPrefix: false   #不添加路由前缀===========

zuul.routes.consumer.path: /consumer/**   #这里是映射路径
zuul.routes.consumer.service-id: helios-consumer-service   #指定服务名称
zuul.routes.consumer.stripPrefix: false   #不添加路由前缀===========

helios:
  releaseMethods: /dataManagement/offlineDataUpload,/systemMonitor/importLogs,/Api/iris/regIris,/Api/iris/irisInspection,/Api/iris/irisCheck,/common/desEncrypt,/common/desDecode,/Api/iris/regIris/,/Api/iris/irisInspection/,/Api/iris/irisCheck/,/collection/gather/checkDevice,/collection/gather/getDriveVersion,/SysManage/DriveManage/getNewDrive,/Api/gdjz/reg,/Api/gdjz/getCodeList,/Api/personApi/getPersonInfo,/common/editSdkIp,/Api/iris/irisLinkage/,/Api/iris/irisLinkage,/Api/iris/sync,/Api/iris/sync/,/Api/iris/identifyByCjsbbh,/Api/iris/identifyByCjsbbh/,/collection/gather/getCodeList,/SysManage/DriveManage/queryDrivesByManufacturer,/SysManage/DriveManage/queryMicroServiceInfo,/SysManage/DriveManage/getNewDrive,/dataQuery/checkList,/Api/xiamen/irisRegister

loginToken:
  timeout: 3600
  prefix: LoginToken_
  whiteList: 666666