
server:
  port: 9080

spring:
  application:
    name: zuul-gateway
  cloud:
    loadbalancer:
      retry:
        #  据说ribbon重试默认已经开启
        enabled: true
    config:
      # uri: http://localhost:8088/
      discovery:
        enabled: true
        serviceId: config-server
      # profile: test
      profile: dev
      fail-fast: true
      retry:
        multiplier: 1000
        max-attempts: 10
eureka:
  instance:
    prefer-ip-address: true #注册服务的ip
  client:
    register-with-eureka: true #使用Eureka注册服务
    fetch-registry: true #在本地缓存注册表
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #Eureka服务位置


zuul:
  host:
    max-per-route-connections: 1500
    max-total-connections: 1500
  semaphore:
    max-semaphores: 3000

